version: "3.7"
services:
  database:
    image: postgres:12.2
    environment:
      POSTGRES_USER: pagila
      POSTGRES_PASSWORD: pagila
      POSTGRES_DB: pagila
      PGDATA: /tmp
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

